CREATE TABLE [dbo].[TBL_CUSTOMER_ACCOUNT] (
    [CUSTOMER_ACCOUNT_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [CUSTOMER_ID]         BIGINT         NOT NULL,
    [ACCOUNT_ID]          BIGINT         NOT NULL,
    [ENTRY_USER_ID]       BIGINT         NOT NULL,
    [ENTRY_DATE]          DATE           CONSTRAINT [DF_TBL_CUSTOMER_ACCOUNT_ENTRY_DATE] DEFAULT (getdate()) NOT NULL,
    [OWNER_ID]            INT            NOT NULL,
    [DESCRIPTION]         NVARCHAR (MAX) DEFAULT ('') NULL,
    [FTS]                 NVARCHAR (MAX) DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TBL_CUSTOMER_ACCOUNT] PRIMARY KEY CLUSTERED ([CUSTOMER_ACCOUNT_ID] ASC),
    CONSTRAINT [FK_TBL_CUSTOMER_ACCOUNT_TBL_ACCOUNT] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[TBL_ACCOUNT] ([ACCOUNT_ID]),
    CONSTRAINT [FK_TBL_CUSTOMER_ACCOUNT_TBL_OWNER] FOREIGN KEY ([OWNER_ID]) REFERENCES [dbo].[TBL_OWNER] ([OWNER_ID]),
    CONSTRAINT [FK_TBL_CUSTOMER_ACCOUNT_TBL_USER] FOREIGN KEY ([ENTRY_USER_ID]) REFERENCES [dbo].[TBL_USER] ([USER_ID])
);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_CUSTOMER_ACCOUNT_CUSTOMER_ID]
    ON [dbo].[TBL_CUSTOMER_ACCOUNT]([CUSTOMER_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_CUSTOMER_ACCOUNT_ACCOUNT_ID]
    ON [dbo].[TBL_CUSTOMER_ACCOUNT]([ACCOUNT_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_ENTRY_USER_ID]
    ON [dbo].[TBL_CUSTOMER_ACCOUNT]([ENTRY_USER_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_OWNER_ID]
    ON [dbo].[TBL_CUSTOMER_ACCOUNT]([OWNER_ID] ASC);


GO

CREATE FULLTEXT INDEX ON [dbo].[TBL_CUSTOMER_ACCOUNT]
    ([FTS] LANGUAGE 1033)
    KEY INDEX [PK_TBL_CUSTOMER_ACCOUNT]
    ON [UCAT_01];


GO

