CREATE TABLE [dbo].[TBL_ACCOUNT] (
    [ACCOUNT_ID]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [CURRENCY]      NVARCHAR (50)   NOT NULL,
    [TITLE]         NVARCHAR (50)   NOT NULL,
    [AMMOUNT]       DECIMAL (18, 2) NOT NULL,
    [ENTRY_USER_ID] BIGINT          NOT NULL,
    [ENTRY_DATE]    DATE            CONSTRAINT [DF_TBL_ACCOUNT_ENTRY_DATE] DEFAULT (getdate()) NOT NULL,
    [OWNER_ID]      INT             NOT NULL,
    [FTS]           NVARCHAR (MAX)  DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TBL_ACCOUNT] PRIMARY KEY CLUSTERED ([ACCOUNT_ID] ASC),
    CONSTRAINT [FK_TBL_ACCOUNT_TBL_OWNER] FOREIGN KEY ([OWNER_ID]) REFERENCES [dbo].[TBL_OWNER] ([OWNER_ID]),
    CONSTRAINT [FK_TBL_ACCOUNT_TBL_USER] FOREIGN KEY ([ENTRY_USER_ID]) REFERENCES [dbo].[TBL_USER] ([USER_ID])
);


GO

CREATE NONCLUSTERED INDEX [IX_OWNER_ID]
    ON [dbo].[TBL_ACCOUNT]([OWNER_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_ENTRY_USER_ID]
    ON [dbo].[TBL_ACCOUNT]([ENTRY_USER_ID] ASC);


GO

CREATE FULLTEXT INDEX ON [dbo].[TBL_ACCOUNT]
    ([FTS] LANGUAGE 1033)
    KEY INDEX [PK_TBL_ACCOUNT]
    ON [UCAT_01];


GO

