CREATE TABLE [dbo].[TBL_UPLOADED_FILE] (
    [UPLOADED_FILE_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [REL_ENTITY]       NVARCHAR (50)  NOT NULL,
    [REL_KEY]          BIGINT         NOT NULL,
    [REL_FIELD]        NVARCHAR (50)  NOT NULL,
    [SIZE]             INT            NOT NULL,
    [EXTENSION]        NVARCHAR (50)  NOT NULL,
    [STAMP]            NVARCHAR (100) NULL,
    [ENTRY_USER_ID]    BIGINT         NOT NULL,
    [ENTRY_DATE]       DATE           CONSTRAINT [DF_TBL_UPLOADED_FILE_ENTRY_DATE] DEFAULT (getdate()) NOT NULL,
    [OWNER_ID]         INT            NOT NULL,
    [FTS]              NVARCHAR (MAX) CONSTRAINT [DF_TBL_UPLOADED_FILE_FTS] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TBL_UPLOADED_FILE] PRIMARY KEY CLUSTERED ([UPLOADED_FILE_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_ENTRY_USER_ID]
    ON [dbo].[TBL_UPLOADED_FILE]([ENTRY_USER_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_OWNER_ID]
    ON [dbo].[TBL_UPLOADED_FILE]([OWNER_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_UPLOADED_FILE]
    ON [dbo].[TBL_UPLOADED_FILE]([REL_ENTITY] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_UPLOADED_FILE_1]
    ON [dbo].[TBL_UPLOADED_FILE]([REL_ENTITY] ASC, [REL_KEY] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_UPLOADED_FILE_2]
    ON [dbo].[TBL_UPLOADED_FILE]([REL_ENTITY] ASC, [REL_KEY] ASC, [REL_FIELD] ASC);


GO

CREATE FULLTEXT INDEX ON [dbo].[TBL_UPLOADED_FILE]
    ([FTS] LANGUAGE 1033)
    KEY INDEX [PK_TBL_UPLOADED_FILE]
    ON [UCAT_01];


GO

