CREATE TABLE [dbo].[TBL_OWNER] (
    [OWNER_ID]             INT            IDENTITY (1, 1) NOT NULL,
    [CODE]                 NVARCHAR (50)  CONSTRAINT [DF_TBL_OWNER_CODE] DEFAULT ('') NULL,
    [MAINTENANCE_DUE_DATE] DATE           CONSTRAINT [DF_TBL_OWNER_MAINTENANCE_DUE_DATE] DEFAULT (getdate()) NULL,
    [DESCRIPTION]          NVARCHAR (200) NOT NULL,
    [ENTRY_DATE]           DATETIME       CONSTRAINT [DF_TBL_OWNER_ENTRY_DATE] DEFAULT (getdate()) NOT NULL,
    [FTS]                  NVARCHAR (MAX) CONSTRAINT [DF_TBL_OWNER_FTS] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TBL_OWNER] PRIMARY KEY CLUSTERED ([OWNER_ID] ASC)
);


GO

CREATE FULLTEXT INDEX ON [dbo].[TBL_OWNER]
    ([FTS] LANGUAGE 1033)
    KEY INDEX [PK_TBL_OWNER]
    ON [UCAT_01];


GO

