CREATE TABLE [dbo].[TBL_USER] (
    [USER_ID]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [OWNER_ID]       INT             NOT NULL,
    [USERNAME]       NVARCHAR (100)  NOT NULL,
    [PASSWORD]       NVARCHAR (1000) NOT NULL,
    [USER_TYPE_CODE] NVARCHAR (50)   NOT NULL,
    [IS_ACTIVE]      BIT             NOT NULL,
    [ENTRY_DATE]     DATE            CONSTRAINT [DF_TBL_USER_ENTRY_DATE] DEFAULT (getdate()) NOT NULL,
    [FTS]            NVARCHAR (MAX)  CONSTRAINT [DF_TBL_USER_FTS] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TBL_USER] PRIMARY KEY CLUSTERED ([USER_ID] ASC),
    CONSTRAINT [FK_TBL_USER_TBL_OWNER] FOREIGN KEY ([OWNER_ID]) REFERENCES [dbo].[TBL_OWNER] ([OWNER_ID])
);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_USER]
    ON [dbo].[TBL_USER]([OWNER_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_USER_1]
    ON [dbo].[TBL_USER]([USERNAME] ASC);


GO

CREATE FULLTEXT INDEX ON [dbo].[TBL_USER]
    ([FTS] LANGUAGE 1033)
    KEY INDEX [PK_TBL_USER]
    ON [UCAT_01];


GO

