CREATE TABLE [dbo].[TBL_SETUP] (
    [OWNER_ID]      INT            NOT NULL,
    [TBL_NAME]      NVARCHAR (50)  NOT NULL,
    [CODE_NAME]     NVARCHAR (50)  NOT NULL,
    [ISSYSTEM]      BIT            CONSTRAINT [DF_TBL_SETUP_ISSYSTEM] DEFAULT ((1)) NOT NULL,
    [ISDELETEABLE]  BIT            CONSTRAINT [DF_TBL_SETUP_ISDELETEABLE] DEFAULT ((1)) NOT NULL,
    [ISUPDATEABLE]  BIT            CONSTRAINT [DF_TBL_SETUP_ISUPDATEABLE] DEFAULT ((1)) NOT NULL,
    [ISDELETED]     BIT            CONSTRAINT [DF_TBL_SETUP_ISDELETED] DEFAULT ((0)) NOT NULL,
    [ISVISIBLE]     BIT            CONSTRAINT [DF_TBL_SETUP_ISVISIBLE] DEFAULT ((1)) NOT NULL,
    [DISPLAY_ORDER] INT            NOT NULL,
    [CODE_VALUE_EN] NVARCHAR (200) NOT NULL,
    [CODE_VALUE_FR] NVARCHAR (200) NOT NULL,
    [CODE_VALUE_AR] NVARCHAR (200) NOT NULL,
    [NOTES]         NVARCHAR (MAX) CONSTRAINT [DF_TBL_SETUP_NOTES] DEFAULT ('') NOT NULL,
    [ENTRY_DATE]    DATE           CONSTRAINT [DF_TBL_SETUP_ENTRY_DATE] DEFAULT (getdate()) NOT NULL,
    [ENTRY_USER_ID] BIGINT         CONSTRAINT [DF_TBL_SETUP_ENTRY_USER_ID] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_TBL_SETUP] PRIMARY KEY CLUSTERED ([OWNER_ID] ASC, [TBL_NAME] ASC, [CODE_NAME] ASC),
    CONSTRAINT [FK_TBL_SETUP_TBL_OWNER] FOREIGN KEY ([OWNER_ID]) REFERENCES [dbo].[TBL_OWNER] ([OWNER_ID]),
    CONSTRAINT [FK_TBL_SETUP_TBL_USER] FOREIGN KEY ([ENTRY_USER_ID]) REFERENCES [dbo].[TBL_USER] ([USER_ID])
);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_SETUP_2]
    ON [dbo].[TBL_SETUP]([TBL_NAME] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_SETUP]
    ON [dbo].[TBL_SETUP]([OWNER_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [IX_TBL_SETUP_1]
    ON [dbo].[TBL_SETUP]([OWNER_ID] ASC, [TBL_NAME] ASC);


GO

