CREATE PROCEDURE [DBO].[UP_BULK_UPSERT_UPLOADED_FILE]
(
@P__JSON_CONTENT AS NVARCHAR(MAX)
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
----------------------
DECLARE @V__LIST_IDs TABLE(ID INT)

DECLARE @V__UPLOADED_FILE_ID AS BIGINT
DECLARE @V__REL_ENTITY AS NVARCHAR(50)
DECLARE @V__REL_KEY AS BIGINT
DECLARE @V__REL_FIELD AS NVARCHAR(50)
DECLARE @V__SIZE AS INT
DECLARE @V__EXTENSION AS NVARCHAR(50)
DECLARE @V__STAMP AS NVARCHAR(100)
DECLARE @V__ENTRY_USER_ID AS BIGINT
DECLARE @V__ENTRY_DATE AS NVARCHAR(20)
DECLARE @V__OWNER_ID AS INT
----------------------
DECLARE CURSOR_JSON_DATA CURSOR FOR
SELECT
UPLOADED_FILE_ID,
REL_ENTITY,
REL_KEY,
REL_FIELD,
SIZE,
EXTENSION,
STAMP,
ENTRY_USER_ID,
ENTRY_DATE,
OWNER_ID
FROM OPENJSON (@P__JSON_CONTENT)
WITH
(
UPLOADED_FILE_ID BIGINT '$.UPLOADED_FILE_ID',
REL_ENTITY NVARCHAR(50) '$.REL_ENTITY',
REL_KEY BIGINT '$.REL_KEY',
REL_FIELD NVARCHAR(50) '$.REL_FIELD',
SIZE INT '$.SIZE',
EXTENSION NVARCHAR(50) '$.EXTENSION',
STAMP NVARCHAR(100) '$.STAMP',
ENTRY_USER_ID BIGINT '$.ENTRY_USER_ID',
ENTRY_DATE NVARCHAR(20) '$.ENTRY_DATE',
OWNER_ID INT '$.OWNER_ID'
)
OPEN CURSOR_JSON_DATA
FETCH NEXT FROM CURSOR_JSON_DATA into @V__UPLOADED_FILE_ID, @V__REL_ENTITY,@V__REL_KEY,@V__REL_FIELD,@V__SIZE,@V__EXTENSION,@V__STAMP,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
WHILE @@FETCH_STATUS = 0
BEGIN
EXEC UPG_EDIT_UPLOADED_FILE @V__UPLOADED_FILE_ID OUTPUT, @V__REL_ENTITY,@V__REL_KEY,@V__REL_FIELD,@V__SIZE,@V__EXTENSION,@V__STAMP,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
INSERT INTO @V__LIST_IDs(ID) VALUES(@V__UPLOADED_FILE_ID)
FETCH NEXT FROM CURSOR_JSON_DATA into @V__UPLOADED_FILE_ID, @V__REL_ENTITY,@V__REL_KEY,@V__REL_FIELD,@V__SIZE,@V__EXTENSION,@V__STAMP,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
END
CLOSE CURSOR_JSON_DATA;
DEALLOCATE CURSOR_JSON_DATA

----------------------
DECLARE @V__IDs AS VARCHAR(8000)
SET @V__IDs = ''
SELECT @V__IDs = @V__IDs + CAST(ID AS NVARCHAR(10)) + ','
FROM   @V__LIST_IDs

EXEC UPG_GET_UPLOADED_FILE_BY_UPLOADED_FILE_ID_LIST @V__IDs
----------------------
END

GO

