CREATE PROCEDURE [DBO].[UP_BULK_UPSERT_USER]
(
@P__JSON_CONTENT AS NVARCHAR(MAX)
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
----------------------
DECLARE @V__LIST_IDs TABLE(ID INT)

DECLARE @V__USER_ID AS BIGINT
DECLARE @V__OWNER_ID AS INT
DECLARE @V__USERNAME AS NVARCHAR(100)
DECLARE @V__PASSWORD AS NVARCHAR(1000)
DECLARE @V__USER_TYPE_CODE AS NVARCHAR(50)
DECLARE @V__IS_ACTIVE AS BIT
DECLARE @V__ENTRY_DATE AS NVARCHAR(20)
----------------------
DECLARE CURSOR_JSON_DATA CURSOR FOR
SELECT
USER_ID,
OWNER_ID,
USERNAME,
PASSWORD,
USER_TYPE_CODE,
IS_ACTIVE,
ENTRY_DATE
FROM OPENJSON (@P__JSON_CONTENT)
WITH
(
USER_ID BIGINT '$.USER_ID',
OWNER_ID INT '$.OWNER_ID',
USERNAME NVARCHAR(100) '$.USERNAME',
PASSWORD NVARCHAR(1000) '$.PASSWORD',
USER_TYPE_CODE NVARCHAR(50) '$.USER_TYPE_CODE',
IS_ACTIVE BIT '$.IS_ACTIVE',
ENTRY_DATE NVARCHAR(20) '$.ENTRY_DATE'
)
OPEN CURSOR_JSON_DATA
FETCH NEXT FROM CURSOR_JSON_DATA into @V__USER_ID, @V__OWNER_ID,@V__USERNAME,@V__PASSWORD,@V__USER_TYPE_CODE,@V__IS_ACTIVE,@V__ENTRY_DATE
WHILE @@FETCH_STATUS = 0
BEGIN
EXEC UPG_EDIT_USER @V__USER_ID OUTPUT, @V__OWNER_ID,@V__USERNAME,@V__PASSWORD,@V__USER_TYPE_CODE,@V__IS_ACTIVE,@V__ENTRY_DATE
INSERT INTO @V__LIST_IDs(ID) VALUES(@V__USER_ID)
FETCH NEXT FROM CURSOR_JSON_DATA into @V__USER_ID, @V__OWNER_ID,@V__USERNAME,@V__PASSWORD,@V__USER_TYPE_CODE,@V__IS_ACTIVE,@V__ENTRY_DATE
END
CLOSE CURSOR_JSON_DATA;
DEALLOCATE CURSOR_JSON_DATA

----------------------
DECLARE @V__IDs AS VARCHAR(8000)
SET @V__IDs = ''
SELECT @V__IDs = @V__IDs + CAST(ID AS NVARCHAR(10)) + ','
FROM   @V__LIST_IDs

EXEC UPG_GET_USER_BY_USER_ID_LIST @V__IDs
----------------------
END

GO

