CREATE PROCEDURE [DBO].[UP_BULK_UPSERT_ACCOUNT]
(
@P__JSON_CONTENT AS NVARCHAR(MAX)
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
----------------------
DECLARE @V__LIST_IDs TABLE(ID INT)

DECLARE @V__ACCOUNT_ID AS BIGINT
DECLARE @V__CURRENCY AS NVARCHAR(50)
DECLARE @V__TITLE AS NVARCHAR(50)
DECLARE @V__AMMOUNT AS DECIMAL(18,2)
DECLARE @V__ENTRY_USER_ID AS BIGINT
DECLARE @V__ENTRY_DATE AS NVARCHAR(20)
DECLARE @V__OWNER_ID AS INT
----------------------
DECLARE CURSOR_JSON_DATA CURSOR FOR
SELECT
ACCOUNT_ID,
CURRENCY,
TITLE,
AMMOUNT,
ENTRY_USER_ID,
ENTRY_DATE,
OWNER_ID
FROM OPENJSON (@P__JSON_CONTENT)
WITH
(
ACCOUNT_ID BIGINT '$.ACCOUNT_ID',
CURRENCY NVARCHAR(50) '$.CURRENCY',
TITLE NVARCHAR(50) '$.TITLE',
AMMOUNT DECIMAL(18,2) '$.AMMOUNT',
ENTRY_USER_ID BIGINT '$.ENTRY_USER_ID',
ENTRY_DATE NVARCHAR(20) '$.ENTRY_DATE',
OWNER_ID INT '$.OWNER_ID'
)
OPEN CURSOR_JSON_DATA
FETCH NEXT FROM CURSOR_JSON_DATA into @V__ACCOUNT_ID, @V__CURRENCY,@V__TITLE,@V__AMMOUNT,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
WHILE @@FETCH_STATUS = 0
BEGIN
EXEC UPG_EDIT_ACCOUNT @V__ACCOUNT_ID OUTPUT, @V__CURRENCY,@V__TITLE,@V__AMMOUNT,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
INSERT INTO @V__LIST_IDs(ID) VALUES(@V__ACCOUNT_ID)
FETCH NEXT FROM CURSOR_JSON_DATA into @V__ACCOUNT_ID, @V__CURRENCY,@V__TITLE,@V__AMMOUNT,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
END
CLOSE CURSOR_JSON_DATA;
DEALLOCATE CURSOR_JSON_DATA

----------------------
DECLARE @V__IDs AS VARCHAR(8000)
SET @V__IDs = ''
SELECT @V__IDs = @V__IDs + CAST(ID AS NVARCHAR(10)) + ','
FROM   @V__LIST_IDs

EXEC UPG_GET_ACCOUNT_BY_ACCOUNT_ID_LIST @V__IDs
----------------------
END

GO

