CREATE PROCEDURE [DBO].[UP_BULK_UPSERT_CUSTOMER_ACCOUNT]
(
@P__JSON_CONTENT AS NVARCHAR(MAX)
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
----------------------
DECLARE @V__LIST_IDs TABLE(ID INT)

DECLARE @V__CUSTOMER_ACCOUNT_ID AS BIGINT
DECLARE @V__CUSTOMER_ID AS BIGINT
DECLARE @V__ACCOUNT_ID AS BIGINT
DECLARE @V__ENTRY_USER_ID AS BIGINT
DECLARE @V__ENTRY_DATE AS NVARCHAR(20)
DECLARE @V__OWNER_ID AS INT
DECLARE @V__DESCRIPTION AS NVARCHAR(MAX)
----------------------
DECLARE CURSOR_JSON_DATA CURSOR FOR
SELECT
CUSTOMER_ACCOUNT_ID,
CUSTOMER_ID,
ACCOUNT_ID,
ENTRY_USER_ID,
ENTRY_DATE,
OWNER_ID,
DESCRIPTION
FROM OPENJSON (@P__JSON_CONTENT)
WITH
(
CUSTOMER_ACCOUNT_ID BIGINT '$.CUSTOMER_ACCOUNT_ID',
CUSTOMER_ID BIGINT '$.CUSTOMER_ID',
ACCOUNT_ID BIGINT '$.ACCOUNT_ID',
ENTRY_USER_ID BIGINT '$.ENTRY_USER_ID',
ENTRY_DATE NVARCHAR(20) '$.ENTRY_DATE',
OWNER_ID INT '$.OWNER_ID',
DESCRIPTION NVARCHAR(MAX) '$.DESCRIPTION'
)
OPEN CURSOR_JSON_DATA
FETCH NEXT FROM CURSOR_JSON_DATA into @V__CUSTOMER_ACCOUNT_ID, @V__CUSTOMER_ID,@V__ACCOUNT_ID,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID,@V__DESCRIPTION
WHILE @@FETCH_STATUS = 0
BEGIN
EXEC UPG_EDIT_CUSTOMER_ACCOUNT @V__CUSTOMER_ACCOUNT_ID OUTPUT, @V__CUSTOMER_ID,@V__ACCOUNT_ID,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID,@V__DESCRIPTION
INSERT INTO @V__LIST_IDs(ID) VALUES(@V__CUSTOMER_ACCOUNT_ID)
FETCH NEXT FROM CURSOR_JSON_DATA into @V__CUSTOMER_ACCOUNT_ID, @V__CUSTOMER_ID,@V__ACCOUNT_ID,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID,@V__DESCRIPTION
END
CLOSE CURSOR_JSON_DATA;
DEALLOCATE CURSOR_JSON_DATA

----------------------
DECLARE @V__IDs AS VARCHAR(8000)
SET @V__IDs = ''
SELECT @V__IDs = @V__IDs + CAST(ID AS NVARCHAR(10)) + ','
FROM   @V__LIST_IDs

EXEC UPG_GET_CUSTOMER_ACCOUNT_BY_CUSTOMER_ACCOUNT_ID_LIST @V__IDs
----------------------
END

GO

