CREATE PROCEDURE [DBO].[UP_BULK_UPSERT_CLIENT]
(
@P__JSON_CONTENT AS NVARCHAR(MAX)
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
----------------------
DECLARE @V__LIST_IDs TABLE(ID INT)

DECLARE @V__CLIENT_ID AS BIGINT
DECLARE @V__NAME AS NVARCHAR(50)
DECLARE @V__FAMILY_NAME AS NVARCHAR(50)
DECLARE @V__DOB AS NVARCHAR(20)
DECLARE @V__ENTRY_USER_ID AS BIGINT
DECLARE @V__ENTRY_DATE AS NVARCHAR(20)
DECLARE @V__OWNER_ID AS INT
----------------------
DECLARE CURSOR_JSON_DATA CURSOR FOR
SELECT
CLIENT_ID,
NAME,
FAMILY_NAME,
DOB,
ENTRY_USER_ID,
ENTRY_DATE,
OWNER_ID
FROM OPENJSON (@P__JSON_CONTENT)
WITH
(
CLIENT_ID BIGINT '$.CLIENT_ID',
NAME NVARCHAR(50) '$.NAME',
FAMILY_NAME NVARCHAR(50) '$.FAMILY_NAME',
DOB NVARCHAR(20) '$.DOB',
ENTRY_USER_ID BIGINT '$.ENTRY_USER_ID',
ENTRY_DATE NVARCHAR(20) '$.ENTRY_DATE',
OWNER_ID INT '$.OWNER_ID'
)
OPEN CURSOR_JSON_DATA
FETCH NEXT FROM CURSOR_JSON_DATA into @V__CLIENT_ID, @V__NAME,@V__FAMILY_NAME,@V__DOB,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
WHILE @@FETCH_STATUS = 0
BEGIN
EXEC UPG_EDIT_CLIENT @V__CLIENT_ID OUTPUT, @V__NAME,@V__FAMILY_NAME,@V__DOB,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
INSERT INTO @V__LIST_IDs(ID) VALUES(@V__CLIENT_ID)
FETCH NEXT FROM CURSOR_JSON_DATA into @V__CLIENT_ID, @V__NAME,@V__FAMILY_NAME,@V__DOB,@V__ENTRY_USER_ID,@V__ENTRY_DATE,@V__OWNER_ID
END
CLOSE CURSOR_JSON_DATA;
DEALLOCATE CURSOR_JSON_DATA

----------------------
DECLARE @V__IDs AS VARCHAR(8000)
SET @V__IDs = ''
SELECT @V__IDs = @V__IDs + CAST(ID AS NVARCHAR(10)) + ','
FROM   @V__LIST_IDs

EXEC UPG_GET_CLIENT_BY_CLIENT_ID_LIST @V__IDs
----------------------
END

GO

