
CREATE PROCEDURE [DBO].[UP_ENGINE_GET_INDEXES]
AS

BEGIN
	-- DECLERATION SECTION.
	-------------------------------------------------------------------------------
	-- 35 IS THE LENGHT OF THE NAME FIELD OF THE MASTER.DBO.SPT_VALUES TABLE
	DECLARE    @V__EMPTY 				VARCHAR(1)
	DECLARE    @V__UNIQUE				VARCHAR(35)
	DECLARE    @V__UNIQUEKEY 			VARCHAR(35)
	DECLARE    @V__CLUSTERED 			VARCHAR(35)
	DECLARE    @V__STATISTICS 			VARCHAR(35)
	DECLARE    @V__PRIMARYKEY 			VARCHAR(35)
	DECLARE    @V__AUTOCREATE 			VARCHAR(35)
	DECLARE    @V__HYPOTETHICAL 			VARCHAR(35)
	DECLARE    @V__STATSNORECOMPUTE 		VARCHAR(35)
	DECLARE    @V__IGNOREDUPLICATEROWS		VARCHAR(35)
	DECLARE	   @V__IGNOREDUPLICATEKEYS 		VARCHAR(35)
	DECLARE    @V__DROP_STATEMENT			VARCHAR(8000)	
	DECLARE    @V__INDEX_TABLE_NAME			VARCHAR(1000)
	DECLARE    @V__DATABASENAME			SYSNAME
	-------------------------------------------------------------------------------


	-- INITIALIZATION SECTION.
	-------------------------------------------------------------------------------
	SELECT @V__EMPTY 		= ''
	SELECT @V__IGNOREDUPLICATEKEYS 	= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 1	     --IGNORE DUPLICATE KEYS
	SELECT @V__UNIQUE 		= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 2 	     --UNIQUE
	SELECT @V__IGNOREDUPLICATEROWS 	= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 4	     --IGNORE DUPLICATE ROWS
	SELECT @V__CLUSTERED 		= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 16        --CLUSTERED
	SELECT @V__HYPOTETHICAL 	= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 32 	     --HYPOTETHICAL
	SELECT @V__STATISTICS		= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 64        --STATISTICS
	SELECT @V__PRIMARYKEY		= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 2048      --PRIMARY KEY
	SELECT @V__UNIQUEKEY 		= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 4096      --UNIQUE KEY
	SELECT @V__AUTOCREATE 		= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 8388608   --AUTO CREATE
	SELECT @V__STATSNORECOMPUTE 	= NAME FROM MASTER.DBO.SPT_VALUES    WHERE TYPE = 'I' AND NUMBER = 16777216  --STATS NO RECOMPUTE	
	SET    @V__INDEX_TABLE_NAME	= 'UT__TBL_INDEXES'
	SET    @V__DROP_STATEMENT	= ''
	-------------------------------------------------------------------------------

	-- DROP IF EXISTS.
	-------------------------------------------------------------------------------
	SET @V__DROP_STATEMENT 		= 'IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N''' + @V__INDEX_TABLE_NAME + ''') AND OBJECTPROPERTY(ID, N''ISUSERTABLE'') = 1)' + 
					   'DROP TABLE ' + @V__INDEX_TABLE_NAME
	EXEC (@V__DROP_STATEMENT)		
	-------------------------------------------------------------------------------

	-------------------------------------------------------------------------------
	SELECT   
		 '[' + UPPER(O.NAME) + ']'	 AS 	'TABLE_NAME',
	 	 I.NAME 			 AS 	'INDEX_NAME',
		 INDID,
	  'INDEXDESCRIPTION' = CONVERT(VARCHAR(210), --BITS 16 OFF, 1, 2, 16777216 ON
	      CASE WHEN (I.STATUS & 16)<>0 		THEN @V__CLUSTERED ELSE 'NON'+@V__CLUSTERED END
	      + CASE WHEN (I.STATUS & 1)<>0 		THEN ', ' +	@V__IGNOREDUPLICATEKEYS ELSE @V__EMPTY END
	      + CASE WHEN (I.STATUS & 2)<>0 		THEN ', ' +	@V__UNIQUE ELSE @V__EMPTY END
	      + CASE WHEN (I.STATUS & 4)<>0 		THEN ', ' +	@V__IGNOREDUPLICATEROWS ELSE @V__EMPTY END
	      + CASE WHEN (I.STATUS & 64)<>0 		THEN ','  + 	@V__STATISTICS ELSE
	      CASE WHEN (I.STATUS & 32)<>0 		THEN ', ' +	@V__HYPOTETHICAL ELSE @V__EMPTY END END
	      + CASE WHEN (I.STATUS & 2048)<>0 		THEN ', ' +	@V__PRIMARYKEY ELSE @V__EMPTY END
	      + CASE WHEN (I.STATUS & 4096)<>0 		THEN ', ' +	@V__UNIQUEKEY ELSE @V__EMPTY END
	      + CASE WHEN (I.STATUS & 8388608)<>0 	THEN ', ' +	@V__AUTOCREATE ELSE @V__EMPTY END
	      + CASE WHEN (I.STATUS & 16777216)<>0	 THEN ', '+	@V__STATSNORECOMPUTE ELSE @V__EMPTY END),
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 1),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 2),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 3),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 4),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 5),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 6),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 7),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 8),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 9),'')  + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 10),'') + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 11),'') + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 12),'') + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 13),'') + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 14),'') + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 15),'') + ',' + 
	  COALESCE(INDEX_COL('[' + UPPER(T.[SCHEMA_NAME]) + '].' + O.NAME,INDID, 16),'') + ','  AS 'INDEXED_FIELDS',
          '[' + UPPER(T.[SCHEMA_NAME]) + ']' AS 'SCHEMA_NAME'
	--INTO [UT__TBL_INDEXES]
	FROM SYSINDEXES I, SYSOBJECTS O ,
	(
		SELECT 
				 [ST].[OBJECT_ID],
				 [ST].[NAME] [TABLE_NAME],
				 [SS].[NAME] [SCHEMA_NAME]
		  FROM   SYS.TABLES [ST] INNER JOIN SYS.SCHEMAS [SS] 
	      ON [ST].[SCHEMA_ID] = [SS].[SCHEMA_ID]
	 ) T
	WHERE I.ID = O.ID 
	AND   T.[OBJECT_ID] = [O].[ID]
	AND   INDID > 0 AND INDID < 255 --ALL THE CLUSTERED (=1), NON CLUSTERD (>1 AND <251), AND TEXT OR IMAGE (=255) 
	      AND O.TYPE = 'U' --USER TABLE
	      --IGNORE THE INDEXES FOR THE AUTOSTAT
	      AND (I.STATUS & 64) = 0 --INDEX WITH DUPLICATES
	      AND (I.STATUS & 8388608) = 0 --AUTO CREATED INDEX
	      AND (I.STATUS & 16777216)= 0 --STATS NO RECOMPUTE
	      --AND [O].[NAME]       = @P__TABLE_NAME
	ORDER BY O.NAME
	 -------------------------------------------------------------------------------

END

GO

