CREATE PROCEDURE [DBO].[UPG_DELETE_UPLOADED_FILE_BY_REL_ENTITY]
(
@P__REL_ENTITY NVARCHAR(100)
)
AS
BEGIN
SET NOCOUNT ON
-------------------------------
DELETE
FROM [TBL_UPLOADED_FILE]
WHERE 
REL_ENTITY = @P__REL_ENTITY
-------------------------------
END

GO

