CREATE PROCEDURE [DBO].[UPG_GET_CUSTOMER_ACCOUNT_BY_CUSTOMER_ID_ADV]
(
@P__CUSTOMER_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
-------------------------------
SELECT *
FROM [DBO].[UDFG_GET_CUSTOMER_ACCOUNT_BY_CUSTOMER_ID_ADV]
(
@P__CUSTOMER_ID
)
-------------------------------
END

GO

