CREATE PROCEDURE [DBO].[UPG_DELETE_CUSTOMER_ACCOUNT_BY_CUSTOMER_ID]
(
@P__CUSTOMER_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
-------------------------------
DELETE
FROM [TBL_CUSTOMER_ACCOUNT]
WHERE 
CUSTOMER_ID = @P__CUSTOMER_ID
-------------------------------
END

GO

