CREATE PROCEDURE [DBO].[UPG_DELETE_UPLOADED_FILE]
(
@P__UPLOADED_FILE_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
DELETE
FROM [TBL_UPLOADED_FILE]
WHERE  UPLOADED_FILE_ID = @P__UPLOADED_FILE_ID 
----------------------------
END

GO

