CREATE PROCEDURE [DBO].[UPG_GET_UPLOADED_FILE_BY_REL_ENTITY_REL_KEY]
(
@P__REL_ENTITY NVARCHAR(100),
@P__REL_KEY BIGINT
)
AS
BEGIN
SET NOCOUNT ON
-------------------------------
SELECT *
FROM [DBO].[UDFG_GET_UPLOADED_FILE_BY_REL_ENTITY_REL_KEY]
(
@P__REL_ENTITY,
@P__REL_KEY
)
-------------------------------
END

GO

