CREATE PROCEDURE [DBO].[UPG_FTS_USER_HANDLER]
(
@P__USER_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
--------------------------------
UPDATE  [TBL_USER]
SET [FTS] = 'USERNAME_' + COALESCE([USERNAME],'') + '|' + 'R_USERNAME_' + REVERSE(COALESCE([USERNAME],'')) + '|' + 'PASSWORD_' + COALESCE([PASSWORD],'') + '|' + 'R_PASSWORD_' + REVERSE(COALESCE([PASSWORD],'')) + '|' + 'USER_TYPE_CODE_' + COALESCE([USER_TYPE_CODE],'') + '|' + 'R_USER_TYPE_CODE_' + REVERSE(COALESCE([USER_TYPE_CODE],'')) 
WHERE USER_ID = @P__USER_ID
--------------------------------
END

GO

