CREATE PROCEDURE [DBO].[UPG_DELETE_CUSTOMER_ACCOUNT]
(
@P__CUSTOMER_ACCOUNT_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
DELETE
FROM [TBL_CUSTOMER_ACCOUNT]
WHERE  CUSTOMER_ACCOUNT_ID = @P__CUSTOMER_ACCOUNT_ID 
----------------------------
END

GO

