CREATE PROCEDURE [DBO].[UPG_EDIT_OWNER]
(
@P__OWNER_ID INT OUTPUT,
@P__CODE NVARCHAR(50),
@P__MAINTENANCE_DUE_DATE NVARCHAR(20),
@P__DESCRIPTION NVARCHAR(200),
@P__ENTRY_DATE NVARCHAR(40)
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
IF (@P__OWNER_ID = -1)
BEGIN
INSERT INTO [TBL_OWNER] 
(
CODE,
MAINTENANCE_DUE_DATE,
DESCRIPTION,
ENTRY_DATE
)
VALUES
(
@P__CODE,
CAST(@P__MAINTENANCE_DUE_DATE AS DATE),
@P__DESCRIPTION,
CAST(@P__ENTRY_DATE AS DATETIME)
)
SET @P__OWNER_ID = SCOPE_IDENTITY()
END
ELSE
BEGIN
UPDATE [TBL_OWNER]
SET
[CODE] = @P__CODE,
[MAINTENANCE_DUE_DATE] = CAST(@P__MAINTENANCE_DUE_DATE AS DATE),
[DESCRIPTION] = @P__DESCRIPTION,
[ENTRY_DATE] = CAST(@P__ENTRY_DATE AS DATETIME)
WHERE OWNER_ID = @P__OWNER_ID
END
----------------------------
END

GO

