CREATE PROCEDURE [DBO].[UPG_EDIT_CUSTOMER_ACCOUNT]
(
@P__CUSTOMER_ACCOUNT_ID BIGINT OUTPUT,
@P__CUSTOMER_ID BIGINT,
@P__ACCOUNT_ID BIGINT,
@P__ENTRY_USER_ID BIGINT,
@P__ENTRY_DATE NVARCHAR(20),
@P__OWNER_ID INT,
@P__DESCRIPTION NVARCHAR(MAX)
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
IF (@P__CUSTOMER_ACCOUNT_ID = -1)
BEGIN
INSERT INTO [TBL_CUSTOMER_ACCOUNT] 
(
CUSTOMER_ID,
ACCOUNT_ID,
ENTRY_USER_ID,
ENTRY_DATE,
OWNER_ID,
DESCRIPTION
)
VALUES
(
@P__CUSTOMER_ID,
@P__ACCOUNT_ID,
@P__ENTRY_USER_ID,
CAST(@P__ENTRY_DATE AS DATE),
@P__OWNER_ID,
@P__DESCRIPTION
)
SET @P__CUSTOMER_ACCOUNT_ID = SCOPE_IDENTITY()
END
ELSE
BEGIN
UPDATE [TBL_CUSTOMER_ACCOUNT]
SET
[CUSTOMER_ID] = @P__CUSTOMER_ID,
[ACCOUNT_ID] = @P__ACCOUNT_ID,
[ENTRY_USER_ID] = @P__ENTRY_USER_ID,
[ENTRY_DATE] = CAST(@P__ENTRY_DATE AS DATE),
[OWNER_ID] = @P__OWNER_ID,
[DESCRIPTION] = @P__DESCRIPTION
WHERE CUSTOMER_ACCOUNT_ID = @P__CUSTOMER_ACCOUNT_ID
END
----------------------------
END

GO

