CREATE PROCEDURE [DBO].[UPG_GET_CUSTOMER_ACCOUNT_BY_CUSTOMER_ACCOUNT_ID]
(
@P__CUSTOMER_ACCOUNT_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
SELECT *
FROM  [dbo].[UDFG_GET_CUSTOMER_ACCOUNT_BY_CUSTOMER_ACCOUNT_ID](@P__CUSTOMER_ACCOUNT_ID)
----------------------------
END

GO

