CREATE PROCEDURE [DBO].[UPG_GET_OWNER_BY_CRITERIA_V2]
(
@P__OWNER_ID INT,
@P__CODE NVARCHAR(50),
@P__MAINTENANCE_DUE_DATE NVARCHAR(100),
@P__DESCRIPTION NVARCHAR(200),
@P__START_ROW	BIGINT,
@P__END_ROW	BIGINT,
@P__TOTAL_COUNT BIGINT OUTPUT
)
AS
BEGIN
SET NOCOUNT ON
---------------------------------

---------------------------------
SET @P__START_ROW = @P__START_ROW + 1;
---------------------------------

WITH DATAENTRIES
AS
(
SELECT
ROW_NUMBER() OVER (ORDER BY [T].[OWNER_ID] DESC) AS ROW,[T].*
FROM [DBO].[UDFG_GET_OWNER_BY_CRITERIA_V2]
(
@P__OWNER_ID,
@P__CODE,
@P__MAINTENANCE_DUE_DATE,
@P__DESCRIPTION
) [T]
)


SELECT 	
[OWNER_ID],
[CODE],
CAST([MAINTENANCE_DUE_DATE] AS NVARCHAR) [MAINTENANCE_DUE_DATE],
[DESCRIPTION],
CONVERT(VARCHAR,[ENTRY_DATE], 126) [ENTRY_DATE]
FROM    DATAENTRIES 
WHERE   ROW BETWEEN (@P__START_ROW) AND (@P__END_ROW)


SELECT @P__TOTAL_COUNT = COUNT(*)
FROM [DBO].[UDFG_GET_OWNER_BY_CRITERIA_V2]
(
@P__OWNER_ID,
@P__CODE,
@P__MAINTENANCE_DUE_DATE,
@P__DESCRIPTION
) [T]

---------------------------------
END

GO

