CREATE PROCEDURE [DBO].[UPG_EDIT_USER]
(
@P__USER_ID BIGINT OUTPUT,
@P__OWNER_ID INT,
@P__USERNAME NVARCHAR(100),
@P__PASSWORD NVARCHAR(1000),
@P__USER_TYPE_CODE NVARCHAR(50),
@P__IS_ACTIVE BIT,
@P__ENTRY_DATE NVARCHAR(20)
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
IF (@P__USER_ID = -1)
BEGIN
INSERT INTO [TBL_USER] 
(
OWNER_ID,
USERNAME,
PASSWORD,
USER_TYPE_CODE,
IS_ACTIVE,
ENTRY_DATE
)
VALUES
(
@P__OWNER_ID,
@P__USERNAME,
@P__PASSWORD,
@P__USER_TYPE_CODE,
@P__IS_ACTIVE,
CAST(@P__ENTRY_DATE AS DATE)
)
SET @P__USER_ID = SCOPE_IDENTITY()
END
ELSE
BEGIN
UPDATE [TBL_USER]
SET
[OWNER_ID] = @P__OWNER_ID,
[USERNAME] = @P__USERNAME,
[PASSWORD] = @P__PASSWORD,
[USER_TYPE_CODE] = @P__USER_TYPE_CODE,
[IS_ACTIVE] = @P__IS_ACTIVE,
[ENTRY_DATE] = CAST(@P__ENTRY_DATE AS DATE)
WHERE USER_ID = @P__USER_ID
END
----------------------------
END

GO

