CREATE PROCEDURE [DBO].[UPG_GET_UPLOADED_FILE_BY_CRITERIA]
(
@P__OWNER_ID INT,
@P__REL_ENTITY NVARCHAR(50),
@P__REL_FIELD NVARCHAR(50),
@P__EXTENSION NVARCHAR(50),
@P__STAMP NVARCHAR(100),
@P__START_ROW	BIGINT,
@P__END_ROW	BIGINT,
@P__TOTAL_COUNT BIGINT OUTPUT
)
AS
BEGIN
SET NOCOUNT ON
---------------------------------

---------------------------------
SET @P__START_ROW = @P__START_ROW + 1;
---------------------------------

WITH DATAENTRIES
AS
(
SELECT
ROW_NUMBER() OVER (ORDER BY [T].[UPLOADED_FILE_ID] DESC) AS ROW,[T].*
FROM [DBO].[UDFG_GET_UPLOADED_FILE_BY_CRITERIA]
(
@P__OWNER_ID,
@P__REL_ENTITY,
@P__REL_FIELD,
@P__EXTENSION,
@P__STAMP
) [T]
)


SELECT 	
[UPLOADED_FILE_ID],
[REL_ENTITY],
[REL_KEY],
[REL_FIELD],
[SIZE],
[EXTENSION],
[STAMP],
[ENTRY_USER_ID],
CAST([ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE],
[OWNER_ID]
FROM    DATAENTRIES 
WHERE   ROW BETWEEN (@P__START_ROW) AND (@P__END_ROW)


SELECT @P__TOTAL_COUNT = COUNT(*)
FROM [DBO].[UDFG_GET_UPLOADED_FILE_BY_CRITERIA]
(
@P__OWNER_ID,
@P__REL_ENTITY,
@P__REL_FIELD,
@P__EXTENSION,
@P__STAMP
) [T]

---------------------------------
END

GO

