
CREATE PROCEDURE UPG_NORMALIZE_DATA_TYPE
AS
BEGIN
	
		
	------------------------------------
	DECLARE @V__TABLE_NAME  AS NVARCHAR(200)
	DECLARE @V__COLUMN_NAME AS NVARCHAR(200)
	DECLARE @V__DATA_TYPE   AS NVARCHAR(100)
	DECLARE @V__CHARACTER_MAXIMUM_LENGTH AS INT
	DECLARE @V__NUMERIC_PRECISION AS INT
	DECLARE @V__NUMERIC_SCALE AS INT
	DECLARE @V__STATEMENT   AS NVARCHAR(4000)
		
	SET  @V__TABLE_NAME        = ''
	SET  @V__COLUMN_NAME       = ''
	SET  @V__DATA_TYPE         = ''
	SET  @V__CHARACTER_MAXIMUM_LENGTH = 50
	SET  @V__NUMERIC_PRECISION = 18
	SET  @V__NUMERIC_SCALE     = 3
	SET  @V__STATEMENT         = ''	
	------------------------------------

	------------------------------------
	DECLARE TABLE_CURSOR CURSOR FOR
	SELECT 
		   [TABLE_NAME] 
	FROM   INFORMATION_SCHEMA.TABLES
	WHERE  [TABLE_NAME] NOT IN
			(
			   'TBL_USER',
			   'TBL_OWNER',
			   'TBL_SETUP',
			   'TBL_INC'
			)
	AND    [TABLE_NAME] LIKE 'TBL_%'	
	OPEN TABLE_CURSOR
	FETCH NEXT FROM TABLE_CURSOR INTO @V__TABLE_NAME
	WHILE @@FETCH_STATUS = 0
	BEGIN
	
		-- LOOP OVER CHAR & NCHAR FIELDS
		------------	
		DECLARE COLUMN_CURSOR CURSOR FOR
		SELECT 
			   [COLUMN_NAME],
			   [DATA_TYPE],
			   [CHARACTER_MAXIMUM_LENGTH],
			   [NUMERIC_PRECISION],
			   [NUMERIC_SCALE]
		FROM   INFORMATION_SCHEMA.COLUMNS
		WHERE  [TABLE_NAME]  = @V__TABLE_NAME
		
		OPEN COLUMN_CURSOR
		FETCH NEXT FROM COLUMN_CURSOR INTO @V__COLUMN_NAME,@V__DATA_TYPE,@V__CHARACTER_MAXIMUM_LENGTH,@V__NUMERIC_PRECISION,@V__NUMERIC_SCALE
		WHILE @@FETCH_STATUS = 0
		BEGIN
			
					
			-- NVARCHAR
			------------		
			IF (
				(UPPER(@V__DATA_TYPE) = 'CHAR') OR 
				(UPPER(@V__DATA_TYPE) = 'NCHAR')
			   )
			BEGIN
				 BEGIN TRY
				  SET @V__STATEMENT = 'ALTER TABLE ' + @V__TABLE_NAME + ' ALTER COLUMN ' + @V__COLUMN_NAME + ' NVARCHAR(' + CAST(@V__CHARACTER_MAXIMUM_LENGTH  AS NVARCHAR(20)) + ')'
				  --PRINT @V__STATEMENT
				  EXEC SP_EXECUTESQL @V__STATEMENT
				 END TRY
				 BEGIN CATCH
					PRINT @V__TABLE_NAME + 'DESC: .'				
				 END CATCH
			END
			------------
			
		
			
			-- NVARCHAR
			------------		
			IF (
				(UPPER(@V__DATA_TYPE) = 'FLOAT') OR 
				(UPPER(@V__DATA_TYPE) = 'MONEY') OR
				(UPPER(@V__DATA_TYPE) = 'NUMERIC') OR
				(UPPER(@V__DATA_TYPE) = 'REAL')
			   )
			BEGIN
			    BEGIN TRY
				  SET @V__STATEMENT = 'ALTER TABLE ' + @V__TABLE_NAME + ' ALTER COLUMN ' + @V__COLUMN_NAME + ' DECIMAL(18,3)'				
				  --PRINT @V__STATEMENT
				  EXEC SP_EXECUTESQL @V__STATEMENT
				END TRY
				 BEGIN CATCH
					PRINT @V__TABLE_NAME + 'DESC: .'				
				 END CATCH
			END
			------------
						
			
			------------
			FETCH NEXT FROM COLUMN_CURSOR INTO @V__COLUMN_NAME,@V__DATA_TYPE,@V__CHARACTER_MAXIMUM_LENGTH,@V__NUMERIC_PRECISION,@V__NUMERIC_SCALE
			------------
			
		END
		CLOSE COLUMN_CURSOR
		DEALLOCATE COLUMN_CURSOR
		------------
		
		------------
	    FETCH NEXT FROM TABLE_CURSOR INTO @V__TABLE_NAME
	    ------------	    
	END
	CLOSE TABLE_CURSOR
	DEALLOCATE TABLE_CURSOR
	------------------------------------

END

GO

