CREATE PROCEDURE [DBO].[UPG_FTS_UPLOADED_FILE_HANDLER]
(
@P__UPLOADED_FILE_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
--------------------------------
UPDATE  [TBL_UPLOADED_FILE]
SET [FTS] = 'REL_ENTITY_' + COALESCE([REL_ENTITY],'') + '|' + 'R_REL_ENTITY_' + REVERSE(COALESCE([REL_ENTITY],'')) + '|' + 'REL_FIELD_' + COALESCE([REL_FIELD],'') + '|' + 'R_REL_FIELD_' + REVERSE(COALESCE([REL_FIELD],'')) + '|' + 'EXTENSION_' + COALESCE([EXTENSION],'') + '|' + 'R_EXTENSION_' + REVERSE(COALESCE([EXTENSION],'')) + '|' + 'STAMP_' + COALESCE([STAMP],'') + '|' + 'R_STAMP_' + REVERSE(COALESCE([STAMP],'')) 
WHERE UPLOADED_FILE_ID = @P__UPLOADED_FILE_ID
--------------------------------
END

GO

