CREATE PROCEDURE [DBO].[UPG_GET_UPLOADED_FILE_BY_UPLOADED_FILE_ID]
(
@P__UPLOADED_FILE_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
SELECT *
FROM  [dbo].[UDFG_GET_UPLOADED_FILE_BY_UPLOADED_FILE_ID](@P__UPLOADED_FILE_ID)
----------------------------
END

GO

