CREATE PROCEDURE [DBO].[UPG_GET_CUSTOMER_ACCOUNT_BY_ACCOUNT_ID]
(
@P__ACCOUNT_ID BIGINT
)
AS
BEGIN
SET NOCOUNT ON
-------------------------------
SELECT *
FROM [DBO].[UDFG_GET_CUSTOMER_ACCOUNT_BY_ACCOUNT_ID]
(
@P__ACCOUNT_ID
)
-------------------------------
END

GO

