CREATE PROCEDURE [DBO].[UPG_EDIT_ACCOUNT]
(
@P__ACCOUNT_ID BIGINT OUTPUT,
@P__CURRENCY NVARCHAR(50),
@P__TITLE NVARCHAR(50),
@P__AMMOUNT DECIMAL(18,2),
@P__ENTRY_USER_ID BIGINT,
@P__ENTRY_DATE NVARCHAR(20),
@P__OWNER_ID INT
)
AS
BEGIN
SET NOCOUNT ON
----------------------------
IF (@P__ACCOUNT_ID = -1)
BEGIN
INSERT INTO [TBL_ACCOUNT] 
(
CURRENCY,
TITLE,
AMMOUNT,
ENTRY_USER_ID,
ENTRY_DATE,
OWNER_ID
)
VALUES
(
@P__CURRENCY,
@P__TITLE,
@P__AMMOUNT,
@P__ENTRY_USER_ID,
CAST(@P__ENTRY_DATE AS DATE),
@P__OWNER_ID
)
SET @P__ACCOUNT_ID = SCOPE_IDENTITY()
END
ELSE
BEGIN
UPDATE [TBL_ACCOUNT]
SET
[CURRENCY] = @P__CURRENCY,
[TITLE] = @P__TITLE,
[AMMOUNT] = @P__AMMOUNT,
[ENTRY_USER_ID] = @P__ENTRY_USER_ID,
[ENTRY_DATE] = CAST(@P__ENTRY_DATE AS DATE),
[OWNER_ID] = @P__OWNER_ID
WHERE ACCOUNT_ID = @P__ACCOUNT_ID
END
----------------------------
END

GO

