CREATE FUNCTION DBO.UDF_GET_TABLE_BY_PK
(
  @P__COLUMN_NAME AS NVARCHAR(200)
)
RETURNS NVARCHAR(200)
AS
BEGIN

	---------------------------
	DECLARE @V__RETURN_VALUE AS NVARCHAR(200)
	SET     @V__RETURN_VALUE = ''
	---------------------------

	---------------------------
	SELECT 
		  @V__RETURN_VALUE = INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_NAME 
	FROM  INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
		  INNER JOIN   
		  INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
		  ON   
		  INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME  
	WHERE INFORMATION_SCHEMA.KEY_COLUMN_USAGE.COLUMN_NAME     = @P__COLUMN_NAME
	  AND INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE  =  'PRIMARY KEY'
	---------------------------
	
	---------------------------
	RETURN @V__RETURN_VALUE
	---------------------------
	 
END

GO

