CREATE FUNCTION DBO.UDF_GET_TABLE_FKS
(  
   @P__TABLE_NAME AS NVARCHAR(200)  
)  
RETURNS @__TABLE_INDEXES TABLE     
(    
 [CONSTRAINT_NAME]  NVARCHAR(400),    
 [TABLE_NAME]  NVARCHAR(400),    
 [COLUMN_NAME]  NVARCHAR(400),  
 [FK_ORDINAL_POSITION]    INT,  
 [REFERENCED_CONSTRAINT_NAME]   NVARCHAR(400),    
 [REFERENCED_TABLE_NAME] NVARCHAR(400),
 [REFERENCED_COLUMN_NAME] NVARCHAR(400),
 [REFERENCED_ORDINAL_POSITION] NVARCHAR(400)
)  
AS
BEGIN

	INSERT INTO @__TABLE_INDEXES
	SELECT    
		 KCU1.CONSTRAINT_NAME AS FK_CONSTRAINT_NAME   
		,KCU1.TABLE_NAME AS FK_TABLE_NAME   
		,KCU1.COLUMN_NAME AS FK_COLUMN_NAME   
		,CAST(KCU1.ORDINAL_POSITION AS NVARCHAR) AS FK_ORDINAL_POSITION   
		,KCU2.CONSTRAINT_NAME AS REFERENCED_CONSTRAINT_NAME   
		,KCU2.TABLE_NAME AS REFERENCED_TABLE_NAME   
		,KCU2.COLUMN_NAME AS REFERENCED_COLUMN_NAME   
		,CAST(KCU2.ORDINAL_POSITION AS NVARCHAR) AS REFERENCED_ORDINAL_POSITION   
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC   
	  
	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU1   
		ON KCU1.CONSTRAINT_CATALOG = RC.CONSTRAINT_CATALOG    
		AND KCU1.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA   
		AND KCU1.CONSTRAINT_NAME = RC.CONSTRAINT_NAME   
	  
	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU2   
		ON KCU2.CONSTRAINT_CATALOG = RC.UNIQUE_CONSTRAINT_CATALOG    
		AND KCU2.CONSTRAINT_SCHEMA = RC.UNIQUE_CONSTRAINT_SCHEMA   
		AND KCU2.CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME   
		AND KCU2.ORDINAL_POSITION = KCU1.ORDINAL_POSITION   
	WHERE KCU1.TABLE_NAME = @P__TABLE_NAME

	RETURN

END

GO

