
CREATE FUNCTION DBO.UDF_GET_TABLE_INDEXES
(
   @P__TABLE_NAME AS NVARCHAR(200)
)
RETURNS @__TABLE_INDEXES TABLE   
(  
 [TABLE_NAME]  NVARCHAR(400),  
 [COLUMN_NAME] NVARCHAR(400),  
 [INDEX_NAME]  NVARCHAR(400),
 [INDEX_ID]    INT,
 [COLUMN_ID]   INT
)
AS
BEGIN
INSERT INTO @__TABLE_INDEXES
SELECT 
     TABLENAME = T.NAME,
     COLUMNNAME = COL.NAME,
     INDEXNAME = IND.NAME,
     INDEXID = IND.INDEX_ID,
     COLUMNID = IC.INDEX_COLUMN_ID     
FROM 
     SYS.INDEXES IND 
INNER JOIN 
     SYS.INDEX_COLUMNS IC ON  IND.OBJECT_ID = IC.OBJECT_ID AND IND.INDEX_ID = IC.INDEX_ID 
INNER JOIN 
     SYS.COLUMNS COL ON IC.OBJECT_ID = COL.OBJECT_ID AND IC.COLUMN_ID = COL.COLUMN_ID 
INNER JOIN 
     SYS.TABLES T ON IND.OBJECT_ID = T.OBJECT_ID 
WHERE T.NAME = @P__TABLE_NAME  
ORDER BY 
     T.NAME, IND.NAME, IND.INDEX_ID, IC.INDEX_COLUMN_ID

RETURN
     
END

GO

