CREATE FUNCTION [DBO].[UDFG_GET_UPLOADED_FILE_BY_WHERE]
(
@P__OWNER_ID INT,
@P__REL_ENTITY NVARCHAR(50),
@P__REL_FIELD NVARCHAR(50),
@P__EXTENSION NVARCHAR(50),
@P__STAMP NVARCHAR(100)
)
RETURNS @P__TABLE_UPLOADED_FILE TABLE 
(
[UPLOADED_FILE_ID] BIGINT,
[REL_ENTITY] NVARCHAR(50),
[REL_KEY] BIGINT,
[REL_FIELD] NVARCHAR(50),
[SIZE] INT,
[EXTENSION] NVARCHAR(50),
[STAMP] NVARCHAR(100),
[ENTRY_USER_ID] BIGINT,
[ENTRY_DATE] NVARCHAR(20),
[OWNER_ID] INT
)
AS
BEGIN
---------------------------------

-- DECLARATION SECTION
----------------------------
DECLARE @V__REL_ENTITY AS NVARCHAR(50)
DECLARE @V__REL_FIELD AS NVARCHAR(50)
DECLARE @V__EXTENSION AS NVARCHAR(50)
DECLARE @V__STAMP AS NVARCHAR(100)
----------------------------

----------------------------

SET @V__REL_ENTITY = COALESCE(@P__REL_ENTITY,'')
SET @V__REL_ENTITY = '%' + @V__REL_ENTITY + '%'


SET @V__REL_FIELD = COALESCE(@P__REL_FIELD,'')
SET @V__REL_FIELD = '%' + @V__REL_FIELD + '%'


SET @V__EXTENSION = COALESCE(@P__EXTENSION,'')
SET @V__EXTENSION = '%' + @V__EXTENSION + '%'


SET @V__STAMP = COALESCE(@P__STAMP,'')
SET @V__STAMP = '%' + @V__STAMP + '%';

WITH DATAENTRIES
AS
(
SELECT
[T].*
FROM  [DBO].[TBL_UPLOADED_FILE] [T]  WITH (NOLOCK)
WHERE 
(COALESCE([REL_ENTITY],'') LIKE @V__REL_ENTITY) AND 
(COALESCE([REL_FIELD],'') LIKE @V__REL_FIELD) AND 
(COALESCE([EXTENSION],'') LIKE @V__EXTENSION) AND 
(COALESCE([STAMP],'') LIKE @V__STAMP) 
AND   [OWNER_ID] = @P__OWNER_ID
)
---------------------------------


----------------------------
INSERT INTO @P__TABLE_UPLOADED_FILE
SELECT 	
[UPLOADED_FILE_ID],
[REL_ENTITY],
[REL_KEY],
[REL_FIELD],
[SIZE],
[EXTENSION],
[STAMP],
[ENTRY_USER_ID],
CAST([ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE],
[OWNER_ID]
FROM    DATAENTRIES 
----------------------------
RETURN
---------------------------------
---------------------------------
END

GO

