CREATE FUNCTION [DBO].[UDFG_GET_OWNER_BY_OWNER_ID_LIST]
(
@P__OWNER_ID_LIST VARCHAR(8000)
)
RETURNS @P__TABLE_OWNER TABLE 
(
[OWNER_ID] INT,
[CODE] NVARCHAR(50),
[MAINTENANCE_DUE_DATE] NVARCHAR(20),
[DESCRIPTION] NVARCHAR(200),
[ENTRY_DATE] NVARCHAR(40)
)
AS
BEGIN
--------------------------------------
INSERT INTO @P__TABLE_OWNER
SELECT
[OWNER_ID],
[CODE],
CAST([MAINTENANCE_DUE_DATE] AS NVARCHAR) [MAINTENANCE_DUE_DATE],
[DESCRIPTION],
CONVERT(VARCHAR,[ENTRY_DATE], 126) [ENTRY_DATE]
FROM [TBL_OWNER] [OWNER]  WITH (NOLOCK)
WHERE
(
 (
LEN(@P__OWNER_ID_LIST) = 0
 )
 OR 
 (
[OWNER].OWNER_ID IN (SELECT [PART_VALUE] FROM [DBO].[UDF_SPLIT](',',@P__OWNER_ID_LIST))
 )
)
----------------------------

----------------------------
RETURN
----------------------------
END

GO

