CREATE FUNCTION [DBO].[UDFG_GET_ACCOUNT_BY_ACCOUNT_ID]
(
@P__ACCOUNT_ID BIGINT
)
RETURNS @P__TABLE_ACCOUNT TABLE 
(
[ACCOUNT_ID] BIGINT,
[CURRENCY] NVARCHAR(50),
[TITLE] NVARCHAR(50),
[AMMOUNT] DECIMAL(18,2),
[ENTRY_USER_ID] BIGINT,
[ENTRY_DATE] NVARCHAR(20),
[OWNER_ID] INT
)
AS
BEGIN
--------------------------------------
INSERT INTO @P__TABLE_ACCOUNT
SELECT
[ACCOUNT_ID],
[CURRENCY],
[TITLE],
[AMMOUNT],
[ENTRY_USER_ID],
CAST([ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE],
[OWNER_ID]
FROM    [TBL_ACCOUNT] [ACCOUNT]  WITH (NOLOCK)
WHERE   [ACCOUNT].[ACCOUNT_ID] = @P__ACCOUNT_ID
--------------------------------------

--------------------------------------
RETURN
--------------------------------------
END

GO

