CREATE FUNCTION [DBO].[UDFG_GET_UPLOADED_FILE_BY_REL_ENTITY_REL_KEY]
(
@P__REL_ENTITY NVARCHAR(100),
@P__REL_KEY BIGINT
)
RETURNS @P__TABLE_UPLOADED_FILE TABLE 
(
[UPLOADED_FILE_ID] BIGINT,
[REL_ENTITY] NVARCHAR(50),
[REL_KEY] BIGINT,
[REL_FIELD] NVARCHAR(50),
[SIZE] INT,
[EXTENSION] NVARCHAR(50),
[STAMP] NVARCHAR(100),
[ENTRY_USER_ID] BIGINT,
[ENTRY_DATE] NVARCHAR(20),
[OWNER_ID] INT
)
AS
BEGIN
-------------------------------
INSERT INTO @P__TABLE_UPLOADED_FILE 
SELECT
[UPLOADED_FILE_ID],
[REL_ENTITY],
[REL_KEY],
[REL_FIELD],
[SIZE],
[EXTENSION],
[STAMP],
[ENTRY_USER_ID],
CAST([ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE],
[OWNER_ID]
FROM [TBL_UPLOADED_FILE]  WITH (NOLOCK)
WHERE 
REL_ENTITY = @P__REL_ENTITY AND
REL_KEY = @P__REL_KEY
-------------------------------

-------------------------------
RETURN
-------------------------------
END

GO

