CREATE FUNCTION [DBO].[UDFG_GET_CLIENT_BY_CLIENT_ID_LIST]
(
@P__CLIENT_ID_LIST VARCHAR(8000)
)
RETURNS @P__TABLE_CLIENT TABLE 
(
[CLIENT_ID] BIGINT,
[NAME] NVARCHAR(50),
[FAMILY_NAME] NVARCHAR(50),
[DOB] NVARCHAR(20),
[ENTRY_USER_ID] BIGINT,
[ENTRY_DATE] NVARCHAR(20),
[OWNER_ID] INT
)
AS
BEGIN
--------------------------------------
INSERT INTO @P__TABLE_CLIENT
SELECT
[CLIENT_ID],
[NAME],
[FAMILY_NAME],
CAST([DOB] AS NVARCHAR) [DOB],
[ENTRY_USER_ID],
CAST([ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE],
[OWNER_ID]
FROM [TBL_CLIENT] [CLIENT]  WITH (NOLOCK)
WHERE
(
 (
LEN(@P__CLIENT_ID_LIST) = 0
 )
 OR 
 (
[CLIENT].CLIENT_ID IN (SELECT [PART_VALUE] FROM [DBO].[UDF_SPLIT](',',@P__CLIENT_ID_LIST))
 )
)
----------------------------

----------------------------
RETURN
----------------------------
END

GO

