CREATE FUNCTION [DBO].[UDFG_GET_USER_BY_USERNAME_ADV]
(
@P__USERNAME NVARCHAR(200)
)
RETURNS @P__TABLE_USER TABLE 
(
[USER_ID] BIGINT,
[OWNER_ID] INT,
[USERNAME] NVARCHAR(100),
[PASSWORD] NVARCHAR(1000),
[USER_TYPE_CODE] NVARCHAR(50),
[IS_ACTIVE] BIT,
[ENTRY_DATE] NVARCHAR(20)
)
AS
BEGIN
-------------------------------
INSERT INTO @P__TABLE_USER 
SELECT
[USER].[USER_ID],
[USER].[OWNER_ID],
[USER].[USERNAME],
[USER].[PASSWORD],
[USER].[USER_TYPE_CODE],
[USER].[IS_ACTIVE],
CAST([USER].[ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE]
FROM [TBL_USER] [USER]  WITH (NOLOCK)
WHERE 
[USER].USERNAME = @P__USERNAME
-------------------------------

-------------------------------
RETURN
-------------------------------
END

GO

