CREATE FUNCTION [DBO].[UDFG_GET_UPLOADED_FILE_BY_UPLOADED_FILE_ID_LIST]
(
@P__UPLOADED_FILE_ID_LIST VARCHAR(8000)
)
RETURNS @P__TABLE_UPLOADED_FILE TABLE 
(
[UPLOADED_FILE_ID] BIGINT,
[REL_ENTITY] NVARCHAR(50),
[REL_KEY] BIGINT,
[REL_FIELD] NVARCHAR(50),
[SIZE] INT,
[EXTENSION] NVARCHAR(50),
[STAMP] NVARCHAR(100),
[ENTRY_USER_ID] BIGINT,
[ENTRY_DATE] NVARCHAR(20),
[OWNER_ID] INT
)
AS
BEGIN
--------------------------------------
INSERT INTO @P__TABLE_UPLOADED_FILE
SELECT
[UPLOADED_FILE_ID],
[REL_ENTITY],
[REL_KEY],
[REL_FIELD],
[SIZE],
[EXTENSION],
[STAMP],
[ENTRY_USER_ID],
CAST([ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE],
[OWNER_ID]
FROM [TBL_UPLOADED_FILE] [UPLOADED_FILE]  WITH (NOLOCK)
WHERE
(
 (
LEN(@P__UPLOADED_FILE_ID_LIST) = 0
 )
 OR 
 (
[UPLOADED_FILE].UPLOADED_FILE_ID IN (SELECT [PART_VALUE] FROM [DBO].[UDF_SPLIT](',',@P__UPLOADED_FILE_ID_LIST))
 )
)
----------------------------

----------------------------
RETURN
----------------------------
END

GO

