CREATE FUNCTION [DBO].[UDFG_GET_CLIENT_BY_OWNER_ID_ADV]
(
@P__OWNER_ID INT
)
RETURNS @P__TABLE_CLIENT TABLE 
(
[CLIENT_ID] BIGINT,
[NAME] NVARCHAR(50),
[FAMILY_NAME] NVARCHAR(50),
[DOB] NVARCHAR(20),
[ENTRY_USER_ID] BIGINT,
[ENTRY_DATE] NVARCHAR(20),
[OWNER_ID] INT
)
AS
BEGIN
-------------------------------
INSERT INTO @P__TABLE_CLIENT 
SELECT
[CLIENT].[CLIENT_ID],
[CLIENT].[NAME],
[CLIENT].[FAMILY_NAME],
CAST([CLIENT].[DOB] AS NVARCHAR) [DOB],
[CLIENT].[ENTRY_USER_ID],
CAST([CLIENT].[ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE],
[CLIENT].[OWNER_ID]
FROM [TBL_CLIENT] [CLIENT]  WITH (NOLOCK)
WHERE 
[CLIENT].OWNER_ID = @P__OWNER_ID
-------------------------------

-------------------------------
RETURN
-------------------------------
END

GO

