CREATE FUNCTION [DBO].[UDFG_GET_USER_BY_USER_ID_LIST]
(
@P__USER_ID_LIST VARCHAR(8000)
)
RETURNS @P__TABLE_USER TABLE 
(
[USER_ID] BIGINT,
[OWNER_ID] INT,
[USERNAME] NVARCHAR(100),
[PASSWORD] NVARCHAR(1000),
[USER_TYPE_CODE] NVARCHAR(50),
[IS_ACTIVE] BIT,
[ENTRY_DATE] NVARCHAR(20)
)
AS
BEGIN
--------------------------------------
INSERT INTO @P__TABLE_USER
SELECT
[USER_ID],
[OWNER_ID],
[USERNAME],
[PASSWORD],
[USER_TYPE_CODE],
[IS_ACTIVE],
CAST([ENTRY_DATE] AS NVARCHAR) [ENTRY_DATE]
FROM [TBL_USER] [USER]  WITH (NOLOCK)
WHERE
(
 (
LEN(@P__USER_ID_LIST) = 0
 )
 OR 
 (
[USER].USER_ID IN (SELECT [PART_VALUE] FROM [DBO].[UDF_SPLIT](',',@P__USER_ID_LIST))
 )
)
----------------------------

----------------------------
RETURN
----------------------------
END

GO

