CREATE FUNCTION [DBO].[UDFG_GET_UPLOADED_FILE_BY_CRITERIA]
(
@P__OWNER_ID INT,
@P__REL_ENTITY NVARCHAR(50),
@P__REL_FIELD NVARCHAR(50),
@P__EXTENSION NVARCHAR(50),
@P__STAMP NVARCHAR(100)
)
RETURNS @P__TABLE_UPLOADED_FILE TABLE 
(
[UPLOADED_FILE_ID] BIGINT,
[REL_ENTITY] NVARCHAR(50),
[REL_KEY] BIGINT,
[REL_FIELD] NVARCHAR(50),
[SIZE] INT,
[EXTENSION] NVARCHAR(50),
[STAMP] NVARCHAR(100),
[ENTRY_USER_ID] BIGINT,
[ENTRY_DATE] NVARCHAR(20),
[OWNER_ID] INT
)
AS
BEGIN
---------------------------------



----------------------------
INSERT INTO @P__TABLE_UPLOADED_FILE
SELECT *
FROM [DBO].[UDFG_GET_UPLOADED_FILE_BY_WHERE]
(
@P__OWNER_ID,
@P__REL_ENTITY,
@P__REL_FIELD,
@P__EXTENSION,
@P__STAMP
)
----------------------------

----------------------------
RETURN
---------------------------------
---------------------------------
END

GO

